# base Image

FROM golang:1.18-alphine as builder

RUN mkdir /app

COPY . /app

WORKDIR /app

RUN CGO_ENABLE=0 go build -o brokerApp ./cmd/api

RUN chmod +x /app/brokerApp



# build Tiny Docker Image

FROM alpine:latest

RUN mkdir /app

COPY --from=builder /app/BrokerApp /app

CMD ["/app/BrokerApp"]

